// <auto-generated />
namespace StaffPositions.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddDevelopers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDevelopers));
        
        string IMigrationMetadata.Id
        {
            get { return "201810211223461_AddDevelopers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
